{
	"version": 1523863544,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player1-sheet0.png",
		"images/player2-sheet0.png",
		"images/piso-sheet0.png",
		"images/tiledbackground.png",
		"images/port1-sheet0.png",
		"images/port2-sheet0.png",
		"images/balon-sheet0.png",
		"images/guayos-sheet0.png",
		"images/catapult-sheet0.png",
		"images/zp1-sheet0.png",
		"images/carap1-sheet0.png",
		"images/carap1-sheet1.png",
		"images/carap1-sheet2.png",
		"images/guayos2-sheet0.png",
		"images/carap2-sheet0.png",
		"images/carap2-sheet1.png",
		"images/carap2-sheet2.png",
		"images/tiledbackground2.png",
		"images/btemp-sheet0.png",
		"images/btn_izq-sheet0.png",
		"images/btn_der-sheet0.png",
		"images/btn_jump-sheet0.png",
		"images/btn_pat-sheet0.png",
		"images/salir-sheet0.png",
		"media/ambiente partido de futbol - efectos de sonido.ogg",
		"media/grito de gol - hinchada. (audio).ogg",
		"media/beep2.ogg",
		"media/waving flag (k'naan y david bisbal con letras).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}